#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & 10 Buster 64 bit               #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified by IRWAN MOHI                        #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# IRWAN MOHI                                    #"
echo -e "# Allah                                         #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# Owner VPS                                     #"
echo -e "# Aidan.MY                                      #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="